#!/usr/bin/env python

SECURE_TOKEN_NUM_BYTES = 64
ENCODING = 'UTF-8'
HASH_ALGORITHM = 'sha512'
HASH_ITERATIONS = 100000
HASH_SALT_NUM_BYTES = 32
POSTGRES_DB_CONNECT = "dbname=mapzest user=timarterbury"
MIN_PASSWORD_STR_LENGTH = 8
MAX_PASSWORD_STR_LENGTH = 1024
